### PR TITLE
More testimonials

### PR DESCRIPTION
**Pull request by alexanselmo**
Changes content to excerpt to to support this change:

'Implement “more…” link for testimonials on home page.'

Post configuration change adding the quote from each post to the excerpt section must be moved through the environments as well.

screen shot 2017-08-29 at 3 18 21 pm

### CODE REVIEW

**Comment by alexanselmo** [comment]
bitmoji

**Comment by RobBlack90** [comment]
bitmoji

**Comment by alexanselmo** [comment]
bitmoji

**Comment by Doorwayshousing** [comment]
JajajajajajajajaaaAAAA!!!!!
stephentyler

**Pull request merged**
